// Generated by https://quicktype.io

export interface UserPurchases {
  id:        number;
  title:     string;
  posterUrl: string;
  price:     number;
  purchases: Purchases;
}

export interface Purchases {
  id:               number;
  purchaseNumber:   string;
  purchaseDateTime: string;
}
