// Generated by https://quicktype.io

export interface UserDetails {
  id:          number;
  firstName:   string;
  lastName:    string;
  dateOfBirth: string;
  email:       string;
  phoneNumber: string;
}
